title: Aquilah Jourdain # 
logo: "/image/logo.jpg?raw=true" # 
description: > # 
  Looking to make communication and understandng accessible, one word at a time. 
  <br><br>
  <br><br>
  <a href="www.linkedin.com/in/aquilah-jourdain/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # 
