title: Aquilah Jourdain-Donaldson # 
logo: "/image/logo.jpg?raw=true" # 
description: > # 
  A NYC based technical writer with a rich background in integrations, project management, and process documentation. 
  <br><br>
  <br><br>
  <a href="www.linkedin.com/in/aquilah-jourdain/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # 
