title: Aquilah Jourdain # your name (or website title) here
logo: "/images/thumbnail_image0.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Looking to make communication and understandng accessible, one word at a time. 
  <br><br>
  <a href="https://www.linkedin.com/in/aquilah-jourdain-73818359/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
